# Basic
title: 夜貓工程師成長日記
subtitle: 吾生也有涯，而知也無涯。以有涯隨無涯，殆已。
welcome_message: 嗨，我是ElbertKuo，一名軟體工程師。
description: Those who bring sunshine into the lives of others, cannot keep it from themselves.
creator: <a href="https://ElbertKuo.github.io">@ElbertKuo</a>

url: "https://ElbertKuo.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://3.112.137.134/1/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: elbertkuo
    # duoshuo:

# Social
social:
    github: ElbertKuo
    mail: ElbertKuo23@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
